### ISSUE TITLE
Marketplace VM Solution - Update all fields that require text input to dropdown menus

### ISSUE THREAD

**Issue by swilliams11** [GoogleCloudPlatform/datashare-toolkit#247]
Determine if the text box fields below can be converted to drop-down menus instead, which would prevent the user from entering invalid data and the build failing.

![image](https://user-images.githubusercontent.com/5075006/87855902-ffea5c00-c8e0-11ea-914c-03845d9ac047.png)

**Comment by swilliams11** [comment]
Zone field in the `jinja.display`
```
zone:
    type: string
    default: us-central1-c
    x-googleProperty:
      type: GCE_ZONE
      gceZone:
        whitelistedZones:
        - asia-east1-a
        - asia-east1-b
        - asia-east1-c
        - asia-southeast1-a
        - asia-southeast1-b
        - asia-southeast1-c
        - europe-west1-b
        - europe-west1-c
        - europe-west1-d
        - europe-west4-a
        - europe-west4-b
        - europe-west4-c
        - us-central1-a
        - us-central1-b
        - us-central1-c
        - us-central1-f
        - us-east1-b
        - us-east1-c
        - us-east1-d
        - us-east4-a
        - us-east4-b
        - us-east4-c
        - us-west1-a
        - us-west1-b
        - us-west1-c
```

**Comment by swilliams11** [comment]
GCE Region - Check if this is will work. 

```
zone:
    type: string
    default: us-central1-c
    x-googleProperty:
      type: GCE_REGION
      gceRegion:
        whitelistedRegionss:
        - asia-east1
        - asia-southeast1
        - europe-west1
        - europe-west4
        - us-central1
        - us-east1
        - us-east4
        - us-west1
```
